(append (let ((fujiWhite     "#DCD7BA")
	      (oldWhite      "#C8C093")
	      (sumiInk-0     "#16161D")
	      (sumiInk-1b    "#181820")
	      (sumiInk-1     "#1F1F28")
	      (sumiInk-2     "#2A2A37")
	      (sumiInk-3     "#363646")
	      (sumiInk-4     "#54546D")
	      (waveBlue-1    "#223249")
	      (waveBlue-2    "#2D4F67")
	      (waveAqua1     "#6A9589")
	      (waveAqua2     "#7AA89F")
	      (winterGreen   "#2B3328")
	      (winterYellow  "#49443C")
	      (winterRed     "#43242B")
	      (winterBlue    "#252535")
	      (autumnGreen   "#76946A")
	      (autumnRed     "#C34043")
	      (autumnYellow  "#DCA561")
	      (samuraiRed    "#E82424")
	      (roninYellow   "#FF9E3B")
	      (dragonBlue    "#658594")
	      (fujiGray      "#727169")
	      (springViolet1 "#938AA9")
	      (oniViolet     "#957FB8")
	      (crystalBlue   "#7E9CD8")
	      (springViolet2 "#9CABCA")
	      (springBlue    "#7FB4CA")
	      (lightBlue     "#A3D4D5")
	      (springGreen   "#98BB6C")
	      (boatYellow1   "#938056")
	      (boatYellow2   "#C0A36E")
	      (carpYellow    "#E6C384")
	      (sakuraPink    "#D27E99")
	      (waveRed       "#E46876")
	      (peachRed      "#FF5D62")
	      (surimiOrange  "#FFA066")
	      (katanaGray    "#717C7C")
	      (comet         "#54536D"))
	  `((dark-fg . ,fujiWhite)
	    (dark-bg  . ,sumiInk-1b)
	    (dark-bg-2  . ,sumiInk-2)
	    (dark-bg-3  . ,sumiInk-4)

	    (light-fg . ,sumiInk-0)
	    (light-bg . ,fujiWhite)
	    (light-bg-2  . ,oldWhite)
	    (light-bg-3  . ,carpYellow)

	    (accent . ,springGreen)

	    (keyword . ,sakuraPink)
	    (preprocessor . ,boatYellow2)
	    (type . ,waveAqua2)
	    (string . ,springGreen)
	    (builtin . ,springBlue)
	    (reference . ,peachRed)
	    (constant . ,carpYellow)
	    (comment . ,fujiGray)
	    (function . ,crystalBlue)
	    (variable . ,waveRed)
	    (negation . ,peachRed)
	    (macro . ,peachRed)

	    (finished . ,dragonBlue)

	    (green .  ,springGreen)
	    (black .  ,sumiInk-0)
	    (cyan .  ,waveAqua2)
	    (magenta .  ,sakuraPink)
	    (blue .  ,crystalBlue)
	    (red .  ,peachRed)
	    (white .  ,fujiWhite)
	    (yellow .  ,autumnYellow)
	    (bright-white .  ,oldWhite)
	    (orange .  ,surimiOrange)))
	'((font-family . "Victor Mono")))
