alias pacman='sudo pacman'
alias dnf='sudo dnf'
alias yt-dlp='python3 -m yt_dlp'
which mpv &> /dev/null || alias mpv='flatpak run io.mpv.Mpv'
alias flac-add-numbers='for i in *.flac; do metaflac --set-tag=tracknumber="$(echo $i | cut -c 1-2)" "$i"; done'
alias flac-add-art='metaflac *.flac --import-picture-from=$1'
alias flac-from-other='for i in *.mp3 *.wav *.ogg; do ffmpeg -i "$i" "$(echo $i | cut -d . -f 1).flac"; done'
